version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: rebook
      MYSQL_DATABASE: rebook
      MYSQL_USER: rebook
      MYSQL_PASSWORD: rebook
    ports:
      - "31234:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  blue:
    image: sadang-boogi/howread-api:latest
    container_name: blue
    restart: always
    ports:
      - 8081:8080
  green:
    image: sadang-boogi/howread-api:latest
    container_name: green
    restart: always
    ports:
      - 8082:8080

volumes:
  mysqldata:
